name: CI Pipeline
on:
  push:
    branches:
      - main
      - stag
  pull_request:
    branches:
      - main
      - stag
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'stag'
        type: choice
        options:
          - main
          - stag

jobs:
  call-reusable-workflow:
    uses: NT505-P21-KLTN-ThienLM-PhuongQTH/CI-dashboard-monitoring/.github/workflows/main.yml@main
    with:
      branch: ${{ github.event.inputs.branch || github.ref_name }}
    secrets: inherit
